/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_watcher_AppleFileSystemApi */

#ifndef _Included_com_swoval_watcher_AppleFileSystemApi
#define _Included_com_swoval_watcher_AppleFileSystemApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swoval_watcher_AppleFileSystemApi
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi
 * Method:    init
 * Signature: (Ljava/util/function/Consumer;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_watcher_AppleFileSystemApi_init
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi
 * Method:    loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_loop
  (JNIEnv *, jclass);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi
 * Method:    createStream
 * Signature: (Ljava/lang/String;DIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_watcher_AppleFileSystemApi_createStream
  (JNIEnv *, jclass, jstring, jdouble, jint, jlong);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi
 * Method:    stopStream
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_stopStream
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
