// Do not edit this file manually. It is autogenerated.

package com.swoval.functional

/**
 * Represents an operation that takes an input and returns no result.
 *
 * @tparam T the input type
 */
trait Consumer[T] {

  /**
   * Performs the operation on the given argument.
   *
   * @param t the input argument
   */
  def accept(t: T): Unit

}
