// Do not edit this file manually. It is autogenerated.

package com.swoval.logging

/**
 A debug logger.
 */
trait Logger {

  /**
   * Print a debug message.
   *
   * @param message the message to print.
   */
  def debug(message: String): Unit

}
