/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_files_apple_FileEventsApi */

#ifndef _Included_com_swoval_files_apple_FileEventsApi
#define _Included_com_swoval_files_apple_FileEventsApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    loop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventsApi_loop(JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventsApi_close(JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    init
 * Signature: (Lcom/swoval/functional/Consumer;Lcom/swoval/functional/Consumer;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_files_apple_FileEventsApi_init(JNIEnv *, jclass, jobject,
                                                                       jobject);

/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    createStream
 * Signature: (Ljava/lang/String;DIJ)I
 */
JNIEXPORT jint JNICALL Java_com_swoval_files_apple_FileEventsApi_createStream(JNIEnv *, jclass,
                                                                              jstring, jdouble,
                                                                              jint, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    stopLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventsApi_stopLoop(JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventsApi
 * Method:    stopStream
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventsApi_stopStream(JNIEnv *, jclass, jlong,
                                                                            jint);

#ifdef __cplusplus
}
#endif
#endif
