/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_files_apple_FileEventMonitorImpl */

#ifndef _Included_com_swoval_files_apple_FileEventMonitorImpl
#define _Included_com_swoval_files_apple_FileEventMonitorImpl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    loop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_loop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    init
 * Signature: (Lcom/swoval/functional/Consumer;Lcom/swoval/functional/Consumer;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_init
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    createStream
 * Signature: (Ljava/lang/String;DIJ)I
 */
JNIEXPORT jint JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_createStream
  (JNIEnv *, jclass, jstring, jdouble, jint, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    stopLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_stopLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileEventMonitorImpl
 * Method:    stopStream
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileEventMonitorImpl_stopStream
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
