/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_files_NativeQuickLister */

#ifndef _Included_com_swoval_files_NativeQuickLister
#define _Included_com_swoval_files_NativeQuickLister
#ifdef __cplusplus
extern "C" {
#endif
#undef com_swoval_files_NativeQuickLister_UNKNOWN
#define com_swoval_files_NativeQuickLister_UNKNOWN 0L
#undef com_swoval_files_NativeQuickLister_DIRECTORY
#define com_swoval_files_NativeQuickLister_DIRECTORY 1L
#undef com_swoval_files_NativeQuickLister_FILE
#define com_swoval_files_NativeQuickLister_FILE 2L
#undef com_swoval_files_NativeQuickLister_LINK
#define com_swoval_files_NativeQuickLister_LINK 4L
#undef com_swoval_files_NativeQuickLister_EOF
#define com_swoval_files_NativeQuickLister_EOF 8L
#undef com_swoval_files_NativeQuickLister_ENOENT
#define com_swoval_files_NativeQuickLister_ENOENT -1L
#undef com_swoval_files_NativeQuickLister_EACCES
#define com_swoval_files_NativeQuickLister_EACCES -2L
#undef com_swoval_files_NativeQuickLister_ENOTDIR
#define com_swoval_files_NativeQuickLister_ENOTDIR -3L
#undef com_swoval_files_NativeQuickLister_ESUCCESS
#define com_swoval_files_NativeQuickLister_ESUCCESS -4L
/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    errno
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_swoval_files_NativeQuickLister_errno
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    strerror
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_swoval_files_NativeQuickLister_strerror
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    openDir
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_files_NativeQuickLister_openDir
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    closeDir
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_NativeQuickLister_closeDir
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    nextFile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_files_NativeQuickLister_nextFile
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    getType
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_swoval_files_NativeQuickLister_getType
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_swoval_files_NativeQuickLister
 * Method:    getName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_swoval_files_NativeQuickLister_getName
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
