/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_files_apple_FileSystemApi */

#ifndef _Included_com_swoval_files_apple_FileSystemApi
#define _Included_com_swoval_files_apple_FileSystemApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    loop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileSystemApi_loop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileSystemApi_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    init
 * Signature: (Ljava/util/function/Consumer;Ljava/util/function/Consumer;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_files_apple_FileSystemApi_init
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    createStream
 * Signature: (Ljava/lang/String;DIJ)I
 */
JNIEXPORT jint JNICALL Java_com_swoval_files_apple_FileSystemApi_createStream
  (JNIEnv *, jclass, jstring, jdouble, jint, jlong);

/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    stopLoop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileSystemApi_stopLoop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_swoval_files_apple_FileSystemApi
 * Method:    stopStream
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_swoval_files_apple_FileSystemApi_stopStream
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
