// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import java.util.List

import com.swoval.files.DataViews.Entry
import com.swoval.functional.Filter

trait CachedDirectory[T <: AnyRef]
    extends UpdatableDataView[T]
    with DirectoryView
    with AutoCloseable {

  /**
   * List the children of the path specified by [[CachedDirectory.getPath]], excluding the
   * [[DataViews.Entry entry]] for the path itself. When the maxDepth parameter is <code>-1
   * </code>, return just the entry for the path itself.
   *
   * @param maxDepth the maximum depth of children (see [[DirectoryView.getMaxDepth]])
   * @param filter only include entries matching this filter
   * @return a list containing all of the entries included by the filter up to the max depth.
   */
  def listEntries(maxDepth: Int, filter: Filter[_ >: Entry[T]]): List[Entry[T]]

  /**
   * Returns the [[DataViews.Entry]] associated with the path specified by [[CachedDirectory.getPath]].
   *
   * @return the entry
   */
  def getEntry(): Entry[T]

  /**
 Catch any exceptions in close.
   */
  override def close(): Unit

}
