// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import java.io.IOException

import com.swoval.files.DataViews.Entry

object CachedDirectories {

  /**
   * A callback to fire when a file in a monitored directory is created or deleted.
   *
   * @tparam T The cached value associated with the path
   */
  trait OnChange[T] {

    /**
     * The callback to run when the path changes.
     *
     * @param entry the entry for the updated path
     */
    def apply(entry: Entry[T]): Unit

  }

  /**
   * A callback to fire when a file in a monitor is updated.
   *
   * @tparam T the cached value associated with the path
   */
  trait OnUpdate[T] {

    /**
     * The callback to run when a path is updated.
     *
     * @param oldEntry the previous entry for the updated path
     * @param newEntry the new entry for the updated path
     */
    def apply(oldEntry: Entry[T], newEntry: Entry[T]): Unit

  }

  /**
   * A callback to fire when an error is encountered. This will generally be a [[java.nio.file.FileSystemLoopException]].
   */
  trait OnError {

    /**
     * Apply callback for error.
     *
     * @param exception the encountered error
     */
    def apply(exception: IOException): Unit

  }

}
