// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import java.nio.file.Path
import java.util.List

import com.swoval.functional.Filter

/**
 * A repository for a directory. The [[FileTreeView.list]] method will only
 * return non-empty results for paths that are children of the root directory, specified by [[DirectoryView.getPath]].
 */
trait DirectoryView extends FileTreeView {

  /**
   * Return the path of the root directory.
   *
   * @return the path of the root directory.
   */
  def getPath(): Path

  /**
   * List all of the files in the root directory, returning only those files that are accepted by
   * the provided filter.
   *
   * @param maxDepth the maximum depth of subdirectories to query
   * @param filter include only paths accepted by the filter
   * @return a List of [[java.nio.file.Path]] instances accepted by the filter.
   */
  def list(maxDepth: Int, filter: Filter[_ >: TypedPath]): List[TypedPath]

  /**
   * Returns the maximum depth of children of subdirectories to include below the path specified by
   * [[DirectoryView.getPath]]. For example, when the value is <code>-1</code>, then the
   * DirectoryView should include only itself. When the value is <code>0</code>, it should include
   * all of the subdirectories and files in the path. When the value is <code>1</code>, it should
   * include all of the subdirectories and files in the path and all of the subdirectories and files
   * in the immediate subdirectories of the path, but not the children of these nested
   * subdirectories. When the value is <code>Integer.MAX_VALUE</code>, all children of the path are
   * included.
   *
   * @return the maximum depth of subdirectory children to include.
   */
  def getMaxDepth(): Int

}
