// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import com.swoval.files.SimpleFileTreeView.ListResults
import java.io.IOException

trait DirectoryLister {

  def apply(dir: String, followLinks: Boolean): ListResults

}
