// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import com.swoval.functional.Filters.AllPass
import com.swoval.files.FileTreeDataViews.Entry
import java.io.IOException
import java.nio.file.Path
import java.util.Iterator

class FileCachePathWatcher[T <: AnyRef](private val tree: FileCacheDirectoryTree[T],
                                        private val pathWatcher: PathWatcher[PathWatchers.Event])
    extends AutoCloseable {

  private val symlinkWatcher: SymlinkWatcher = tree.symlinkWatcher

  def register(path: Path, maxDepth: Int): Boolean = {
    val dir: CachedDirectory[T] = tree.register(path, maxDepth, pathWatcher)
    if (dir != null && symlinkWatcher != null) {
      val it: Iterator[Entry[T]] =
        dir.listEntries(dir.getMaxDepth, AllPass).iterator()
      while (it.hasNext) {
        val entry: FileTreeDataViews.Entry[T] = it.next()
        if (entry.isSymbolicLink) {
          val depth: Int = path.relativize(entry.getPath).getNameCount
          symlinkWatcher.addSymlink(entry.getPath,
                                    if (maxDepth == java.lang.Integer.MAX_VALUE) maxDepth
                                    else maxDepth - depth)
        }
      }
    }
    dir != null
  }

  def unregister(path: Path): Unit = {
    tree.unregister(path)
    pathWatcher.unregister(path)
  }

  def close(): Unit = {
    pathWatcher.close()
    symlinkWatcher.close()
  }

}
