// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import com.swoval.files.FileTreeDataViews.Converter
import com.swoval.files.FileTreeViews.Observer
import com.swoval.files.PathWatchers.Event
import java.io.IOException

object FileTreeRepositories {

  /**
   * Create a file tree repository.
   *
   * @param followLinks toggles whether or not to follow symbolic links. When true, any symbolic
   *     links that point to a regular file will trigger an event when the target file is modified.
   *     For any symbolic links that point to a directory, the children of the target directory will
   *     be included (up to the max depth parameter specified by [[    FileTreeRepository.register]]) and will trigger an event when any of the included children
   *     are modified. When false, symbolic links are not followed and only events for the symbolic
   *     link itself are reported.
   * @param converter converts a path to the cached value type T
   * @tparam T the value type of the cache entries
   * @return a file tree repository.
   */
  def get[T <: AnyRef](followLinks: Boolean, converter: Converter[T]): FileTreeRepository[T] = {
    val symlinkWatcher: SymlinkWatcher =
      if (followLinks)
        new SymlinkWatcher(PathWatchers.get(false, new DirectoryRegistryImpl()))
      else null
    val callbackExecutor: Executor =
      Executor.make("FileTreeRepository-callback-executor")
    val tree: FileCacheDirectoryTree[T] =
      new FileCacheDirectoryTree[T](converter, callbackExecutor, symlinkWatcher)
    val pathWatcher: PathWatcher[PathWatchers.Event] =
      PathWatchers.get(false, tree.readOnlyDirectoryRegistry())
    pathWatcher.addObserver(new Observer[Event]() {
      override def onError(t: Throwable): Unit = {}

      override def onNext(event: Event): Unit = {
        tree.handleEvent(event)
      }
    })
    val watcher: FileCachePathWatcher[T] =
      new FileCachePathWatcher[T](tree, pathWatcher)
    new FileTreeRepositoryImpl(tree, watcher)
  }

}
