// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import com.swoval.functional.Either
import java.io.IOException

object FileTreeDataViews {

  /**
   * Container class for [[CachedDirectoryImpl]] entries. Contains both the path to which the
   * path corresponds along with a data value.
   *
   * @tparam T The value wrapped in the Entry
   */
  trait Entry[T] extends TypedPath {

    /**
     * Return the value associated with this entry.
     *jjj
     * @return the value associated with this entry.
     */
    def getValue(): Either[IOException, T]

  }

  /**
   * Converts a Path into an arbitrary value to be cached.
   *
   * @tparam R the generic type generated from the path.
   */
  trait Converter[R] {

    /**
     * Convert the path to a value.
     *
     * @param path the path to convert
     * @return the converted value
     */
    def apply(path: TypedPath): R

  }

  /**
   * A callback to fire when an error is encountered. This will generally be a [[java.nio.file.FileSystemLoopException]].
   */
  trait OnError {

    /**
     * Apply callback for error.
     *
     * @param exception the encountered error
     */
    def apply(exception: IOException): Unit

  }

}
