// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import java.nio.file.Path
import java.util.{ ArrayList, HashMap, Iterator, List, Map }
import java.util.Map.Entry

object MapOps {

  def diffDirectoryEntries[T](oldEntries: List[DataViews.Entry[T]],
                              newEntries: List[DataViews.Entry[T]],
                              cacheObserver: FileTreeViews.CacheObserver[T]): Unit = {
    val oldMap: Map[Path, DataViews.Entry[T]] =
      new HashMap[Path, DataViews.Entry[T]]()
    val oldIterator: Iterator[DataViews.Entry[T]] = oldEntries.iterator()
    while (oldIterator.hasNext) {
      val entry: DataViews.Entry[T] = oldIterator.next()
      oldMap.put(entry.getPath, entry)
    }
    val newMap: Map[Path, DataViews.Entry[T]] =
      new HashMap[Path, DataViews.Entry[T]]()
    val newIterator: Iterator[DataViews.Entry[T]] = newEntries.iterator()
    while (newIterator.hasNext) {
      val entry: DataViews.Entry[T] = newIterator.next()
      newMap.put(entry.getPath, entry)
    }
    diffDirectoryEntries(oldMap, newMap, cacheObserver)
  }

  def diffDirectoryEntries[K, V](oldMap: Map[K, DataViews.Entry[V]],
                                 newMap: Map[K, DataViews.Entry[V]],
                                 cacheObserver: FileTreeViews.CacheObserver[V]): Unit = {
    val newIterator: Iterator[Entry[K, DataViews.Entry[V]]] =
      new ArrayList(newMap.entrySet()).iterator()
    val oldIterator: Iterator[Entry[K, DataViews.Entry[V]]] =
      new ArrayList(oldMap.entrySet()).iterator()
    while (newIterator.hasNext) {
      val entry: Entry[K, DataViews.Entry[V]] = newIterator.next()
      val oldValue: DataViews.Entry[V] = oldMap.get(entry.getKey)
      if (oldValue != null) {
        cacheObserver.onUpdate(oldValue, entry.getValue)
      } else {
        cacheObserver.onCreate(entry.getValue)
      }
    }
    while (oldIterator.hasNext) {
      val entry: Entry[K, DataViews.Entry[V]] = oldIterator.next()
      if (!newMap.containsKey(entry.getKey)) {
        cacheObserver.onDelete(entry.getValue)
      }
    }
  }

}
