// Do not edit this file manually. It is autogenerated.

package com.swoval.files

import com.swoval.files.PathWatchers.Event.Kind
import com.swoval.runtime.Platform
import java.io.IOException
import java.nio.file.Path
import java.util.concurrent.TimeUnit
import scala.beans.{ BeanProperty, BooleanBeanProperty }

object PathWatchers {

  /**
   * Create a PathWatcher for the runtime platform.
   *
   * @param followLinks toggles whether or not the targets of symbolic links should be monitored
   * @return PathWatcher for the runtime platform
   *     initialized
   */
  def get(followLinks: Boolean): PathWatcher[PathWatchers.Event] =
    get(followLinks, new DirectoryRegistryImpl())

  /**
   * Create a path watcher that periodically polls the file system to detect changes
   *
   * @param followLinks toggles whether or not the targets of symbolic links should be monitored
   * @param pollInterval minimum duration between when polling ends and the next poll begins
   * @param timeUnit the time unit for which the pollInterval corresponds
   * @return the polling path watcher.
   */
  def polling(followLinks: Boolean,
              pollInterval: Long,
              timeUnit: TimeUnit): PathWatcher[PathWatchers.Event] =
    new PollingPathWatcher(followLinks, pollInterval, timeUnit)

  /**
   * Create a PathWatcher for the runtime platform.
   *
   * @param followLinks toggles whether or not the targets of symbolic links should be monitored
   * @param registry The registry of directories to monitor
   * @return PathWatcher for the runtime platform
   *     initialized
   */
  def get(followLinks: Boolean, registry: DirectoryRegistry): PathWatcher[Event] =
    if (Platform.isMac) ApplePathWatchers.get(followLinks, registry)
    else PlatformWatcher.make(followLinks, registry)

  /**
   * Create a PathWatcher for the runtime platform.
   *
   * @param registry The registry of directories to monitor
   * @return PathWatcher for the runtime platform
   */
  def get(followLinks: Boolean,
          service: RegisterableWatchService,
          registry: DirectoryRegistry): PathWatcher[Event] =
    PlatformWatcher.make(followLinks, service, registry)

  class Overflow(@BeanProperty val path: Path)

  object Event {

    object Kind {

      /**
 A new file was created.
       */
      val Create: Kind = new Kind("Create")

      /**
 The file was deleted.
       */
      val Delete: Kind = new Kind("Delete")

      /**
 An error occurred processing the event.
       */
      val Error: Kind = new Kind("Error")

      /**
 An existing file was modified.
       */
      val Modify: Kind = new Kind("Modify")

    }

    /**
     * An enum like class to indicate the type of file event. It isn't an actual enum because the
     * scala.js codegen has problems with enum types.
     */
    class Kind(private val name: String) {

      override def toString(): String = name

      override def equals(other: Any): Boolean = other match {
        case other: Kind => other.name == this.name
        case _           => false

      }

      override def hashCode(): Int = name.hashCode

    }

  }

  /**
 Container for [[PathWatcher]] events.
   */
  class Event(@BeanProperty val typedPath: TypedPath, @BeanProperty val kind: Event.Kind) {

    override def equals(other: Any): Boolean = other match {
      case other: Event => {
        val that: Event = other
        this.typedPath == that.typedPath && this.kind == that.kind
      }
      case _ => false

    }

    override def hashCode(): Int = typedPath.hashCode ^ kind.hashCode

    override def toString(): String =
      "Event(" + typedPath.getPath + ", " + kind + ")"

  }

}
