// Do not edit this file manually. It is autogenerated.

package com.swoval.files

trait WatchedDirectory extends AutoCloseable {

  /**
   * Is the underlying directory watcher valid?
   *
   * @return true if the underlying directory watcher is valid
   */
  def isValid(): Boolean

  /**
 Reset any queues for this directory
   */
  def reset(): Unit

  /**
 Cancel the watch on this directory. Handle all non-fatal exceptions.
   */
  override def close(): Unit

}

object WatchedDirectories {

  var INVALID: WatchedDirectory = new WatchedDirectory() {
    override def isValid(): Boolean = false

    override def reset(): Unit = {}

    override def close(): Unit = {}
  }

}
