/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_swoval_watcher_AppleFileSystemApi__ */

#ifndef _Included_com_swoval_watcher_AppleFileSystemApi__
#define _Included_com_swoval_watcher_AppleFileSystemApi__
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_swoval_watcher_AppleFileSystemApi__
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_00024_close
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi__
 * Method:    init
 * Signature: (Lscala/Function1;)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_watcher_AppleFileSystemApi_00024_init
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi__
 * Method:    loop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_00024_loop
  (JNIEnv *, jobject);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi__
 * Method:    createStream
 * Signature: (Ljava/lang/String;DIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_swoval_watcher_AppleFileSystemApi_00024_createStream
  (JNIEnv *, jobject, jstring, jdouble, jint, jlong);

/*
 * Class:     com_swoval_watcher_AppleFileSystemApi__
 * Method:    stopStream
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_swoval_watcher_AppleFileSystemApi_00024_stopStream
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
